### PR TITLE
replaced `len(os.sched_getaffinity(0))` to `os.cpu_count()` works on Windows/OSX/Linux systems.

### PR DESCRIPTION
**Pull request by salman-moh**
These changes are to prevent: 
`AttributeError: module 'os' has no attribute 'sched_getaffinity'`

### CODE REVIEW

**Comment by SGenheden** [comment]
This PR contains more changes than advertised from the title. 
Please only submit one change per PR

**Comment by SGenheden** [comment]
`os.cpu_count()` does not give the correct result on Linux systems.

**Comment by salman-moh** [comment]
Sorry I'll remove the other changes, keeping only the `os.cpu_count()`   -  this is returning me the same value as the `len(os.sched_getaffinity(0))`, what exactly is the incorrect result ?

**Comment by salman-moh** [comment]
@SGenheden please let me know, because I printed out both in my Linux machine and they return the same.

**Pull request closed without merging**
